name: Node.js CI

on:
  push:
    branches: [develop, main]
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    if: | # Refuses to run if not on `main`.
      ! contains('
        refs/heads/main
      ', github.ref)

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          echo ${{ secrets.NPM_REGISTRY }} > ${{ github.workspace }}/.npmrc
          yarn --pure-lockfile --non-interactive --no-progress

      - name: Run ESLint
        run: yarn lint

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Bind localhost to local.mesalva.com
        run: |
          sudo echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts

      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          echo ${{ secrets.NPM_REGISTRY }} > ${{ github.workspace }}/.npmrc
          yarn --pure-lockfile --non-interactive --no-progress

      - name: Run tests
        run: yarn test:coverage
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          API_HOST: ${{ secrets.API_HOST }}
          API_KEY: ${{ secrets.API_KEY }}
          NEXT_PUBLIC_BFF_URL: ${{ secrets.NEXT_PUBLIC_BFF_URL }}
          NEXT_PUBLIC_JSONS_HOST: ${{ secrets.NEXT_PUBLIC_JSONS_HOST }}
          NEXT_PUBLIC_CREDENTIALS_COOKIE_NAME: ${{ secrets.NEXT_PUBLIC_CREDENTIALS_COOKIE_NAME }}
